### ISSUE TITLE
I don't understand the startup instructions.

### ISSUE THREAD

**Issue by kristoffernolgren** [DutchGraa/crackcoin#1]
Cery cool project! I wanted to try it out but ran in to some problems.

Run python generateGenesis.py until a cool address pops up
A bit unclear, can I just pick of the crackXXXX adresses that pop up or will something happen eventually?

Run crackcoin and wait until a confirmation is generated for d34db33f with a higher difficulty (>6) than the one in crackcoinBase.sql 
What does run crackcoin mean? I tried` python crackcoin.py `and then `b`, nothing seems to happen.

Replace the confirmation for d34db33f
Is it the transaction hash I should replace? 

Share code on other nodes
How, who, what now?

I really like this idea, let me know if I can help in any other way than sharing this with friends!

**Comment by spipm** [comment]
Kristoff,

Thank you for your interest in the project.

I agree that the usage section is unclear at the moment. I'll try to update the readme before tomorrow with screenshots and clear instructions.
