### ISSUE TITLE
but how does it work?

### ISSUE THREAD

**Issue by punto-** [DutchGraa/crackcoin#2]
Is there a whitepaper? when is the ICO?

**Comment by spipm** [comment]
Hello Punto,

This is a very simple application to get to know the basics of a cryptocurrency. The application is not based on a whitepaper. However, the idea of not using a blockchain comes from the paper mentioned in the readme. And there will certainly be no ICO: this is a non-profit project meant for educational purposes. No money to me made here.

The application is to provide a simple-as-possible framework to play with a cryptocurrency. Currently the application only allows the transferring of coins from one node to another. Also, the networking part only works on local networks (uses UDP broadcasting).

I'll try to update the usage section in the readme before tomorrow.

**Comment by punto-** [comment]
That was a joke. But a crypto currency with no blockchain is super
interesting, there's millions of blockchains already, you should explain a
bit more at least what the basic concept is (like the IOTA people have
their "Tangle" concept). Anyway, good luck :D

**Comment by spipm** [comment]
Thanks, I'll put it in the readme. :)
